fix: Muda forma de capturar a url e baixa o apk

diff --git a/.github/workflows/buildAPK.yml b/.github/workflows/buildAPK.yml
--- a/.github/workflows/buildAPK.yml
+++ b/.github/workflows/buildAPK.yml
@@ -29,15 +29,23 @@ jobs:
         id: eas_build
         run: |
           eas build --platform android --non-interactive
-          echo "APK_URL=$(eas build:list --status completed --platform android --limit 1 --output json | jq -r '.[0].artifacts.buildUrl')" >> $GITHUB_ENV
+          
+          APK_URL=$(eas build:list --status completed --platform android --profile createAndroidAPK --limit 1 --output json | jq -r '.[0].artifacts.buildUrl' || echo "Error")
 
-      # - name: Download APK
-      #   if: success()
-      #   run: |
-      #     curl -o navGo.apk "$APK_URL"
+          if [ "$APK_URL" = "Error" ]; then
+            echo "Failed to parse APK URL from JSON output. Please check build logs."
+            exit 1
+          else
+            echo "APK_URL=${APK_URL}" >> $GITHUB_ENV
+          fi
 
-      # - name: Upload APK as artifact
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: navGo.apk
-      #     path: navGo.apk
+      - name: Download APK
+        if: success()
+        run: |
+          curl -o navGo.apk "$APK_URL"
+
+      - name: Upload APK as artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: navGo.apk
+          path: navGo.apk
