fix: Usa perfil certo

diff --git a/.github/workflows/buildAPK.yml b/.github/workflows/buildAPK.yml
--- a/.github/workflows/buildAPK.yml
+++ b/.github/workflows/buildAPK.yml
@@ -1,5 +1,7 @@
 on:
-  [push]
+  push:
+    branches:
+      - main
 
 jobs:
   build:
@@ -26,13 +28,12 @@ jobs:
       - name: Build app
         id: eas_build
         run: |
-          BUILD_OUTPUT=$(eas build --platform android --non-interactive)
-          echo "$BUILD_OUTPUT"
-
-          APK_URL=$(echo "$BUILD_OUTPUT" | grep -o 'https://expo.dev/[^ ]*')
+          eas build --platform android --non-interactive --profile createAndroidAPK
           
-          if [ -z "$APK_URL" ]; then
-            echo "Failed to retrieve APK URL from build output."
+          APK_URL=$(eas build:list --status completed --platform android --profile createAndroidAPK --limit 1 --output json | jq -r '.[0].artifacts.buildUrl' || echo "Error")
+
+          if [ "$APK_URL" = "Error" ]; then
+            echo "Failed to parse APK URL from JSON output. Please check build logs."
             exit 1
           else
             echo "APK_URL=${APK_URL}" >> $GITHUB_ENV
